name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "58d86c8e-349a-4dfd-887c-3dd5628e2c19"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
